name: arangoml_demo
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - toolz
  - matplotlib
  - hyperopt
  - pandas
  - scikit-learn
  - pip
  - pip:
    - PyYAML==5.1.1
    - python-arango
    - arangopipe
    
