arangodb:
  arangopipe_admin_password: arangopipe
  arangopipe_admin_username: arangopipe
  arangopipe_dbname: arangopipe
  host: https://7828dc387b41.arangodb.cloud:8529/
  port: 8529
  root_user: root
  root_user_password: 9BZ8pewKqkLdJBh6rq9b
mlgraph:
  graphname: enterprise_ml_graph
