arangodb:
  DB_end_point: apmdb
  DB_service_host: localhost
  DB_service_name: createDB
  DB_service_port: 8529
  arangodb_replication_factor: null
  conn_protocol: http
  dbName: ML5ygsqaz7j6exf1onmuf56k
  email: somebody@some_company.com
  password: MLxazz1nuch6fkzc10p53s
  username: MLk7ogqemw32hmwshtl1ae5q
mlgraph:
  graphname: enterprise_ml_graph
