arangodb:
  DB_end_point: apmdb
  DB_service_host: d874fc3f1fa5.arangodb.cloud
  DB_service_name: createDB
  DB_service_port: 8529
  arangodb_replication_factor: null
  conn_protocol: https
  dbName: MLngscz2uaqleochp7uvzkj
  password: ML3bmi1fwpgugdawuki5fjug
  username: ML3ygm23ysz93xb1ijp5j64s
mlgraph:
  graphname: enterprise_ml_graph
